language: node_js
node_js:
  - "node"
  - "5.11"
  - "4.4"
matrix:
  fast_finish: true
sudo: false
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
